apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  template:
    spec:
      volumes:
      - name: mediavol
        hostPath: 
          path: /home/innsh/dev/temp/media/
      - name: jellyfin-cache-vol
        persistentVolumeClaim:
          claimName: cache
      - name: jellyfin-config-vol
        persistentVolumeClaim:
          claimName: config
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin
        ports: 
          - name: liveness-port
            containerPort: 8096
            protocol: TCP
          - containerPort: 8096
            protocol: TCP
        volumeMounts:
          - name: mediavol
            mountPath: /media/
          - name: jellyfin-cache-vol
            mountPath: /cache
          - name: jellyfin-config-vol
            mountPath: /config
        resources:
          requests:
            memory: "250Mi"
            cpu: 250m
          limits:
            memory: "750Mi"
            cpu: 500m
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          initialDelaySeconds: 10
          periodSeconds: 10
