apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache-storage
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-storage
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 2Mi