apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
  storageClassName: ""
  selector:
    matchLabels:
      storage: config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Mi
  storageClassName: ""
  selector:
    matchLabels:
      storage: cache